# Generated by Django 5.2.7 on 2025-11-03 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feladat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cim', models.CharField(max_length=255)),
                ('leiras', models.TextField()),
                ('letrehozas_datuma', models.DateTimeField(auto_now_add=True)),
                ('hatarido', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Feladatok',
            },
        ),
        migrations.AlterModelOptions(
            name='tantargy',
            options={'verbose_name_plural': 'Tantárgyak'},
        ),
        migrations.CreateModel(
            name='Beadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beadas_datuma', models.DateTimeField(auto_now_add=True)),
                ('szoveges_valasz', models.TextField(blank=True, null=True)),
                ('diak', models.ForeignKey(limit_choices_to={'role': 'diak'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('feladat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beadasok', to='api.feladat')),
            ],
            options={
                'verbose_name_plural': 'Beadások',
            },
        ),
        migrations.CreateModel(
            name='Kurzus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurzus_neve', models.CharField(max_length=255, verbose_name='Kurzus neve (pl. 9.A Matek)')),
                ('diakok', models.ManyToManyField(blank=True, limit_choices_to={'role': 'diak'}, related_name='resztvett_kurzusok', to=settings.AUTH_USER_MODEL)),
                ('tanar', models.ForeignKey(limit_choices_to={'role': 'tanar'}, on_delete=django.db.models.deletion.CASCADE, related_name='oktatott_kurzusok', to=settings.AUTH_USER_MODEL)),
                ('tantargy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurzusok', to='api.tantargy')),
            ],
            options={
                'verbose_name_plural': 'Kurzusok',
            },
        ),
        migrations.AddField(
            model_name='feladat',
            name='kurzus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feladatok', to='api.kurzus'),
        ),
    ]
