# Generated by Django 5.2.7 on 2025-11-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feladat_alter_tantargy_options_beadas_kurzus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pontszam',
            field=models.IntegerField(default=0, verbose_name='Pontszám'),
        ),
    ]
