# Generated by Django 5.2.7 on 2025-11-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_pontszam'),
    ]

    operations = [
        migrations.AddField(
            model_name='beadas',
            name='erdemjegy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Érdemjegy'),
        ),
        migrations.AddField(
            model_name='beadas',
            name='tanari_visszajelzes',
            field=models.TextField(blank=True, null=True, verbose_name='Tanári visszajelzés'),
        ),
    ]
