# Generated by Django 5.2.7 on 2025-11-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_beadas_erdemjegy_beadas_tanari_visszajelzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilkep',
            field=models.ImageField(blank=True, default='profilkepek/default.png', null=True, upload_to='profilkepek/'),
        ),
    ]
