# Generated by Django 5.2.7 on 2026-05-09 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_profilkep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profilkep',
        ),
        migrations.CreateModel(
            name='Hir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cim', models.CharField(max_length=255, verbose_name='Cím')),
                ('tartalom', models.TextField(verbose_name='Tartalom')),
                ('letrehozas_datuma', models.DateTimeField(auto_now_add=True)),
                ('modositas_datuma', models.DateTimeField(auto_now=True)),
                ('szerzo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Szerző')),
            ],
            options={
                'verbose_name_plural': 'Hírek',
                'ordering': ['-letrehozas_datuma'],
            },
        ),
    ]
