# Generated by Django 5.2.7 on 2026-05-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_customuser_profilkep_hir'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUzenet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szoveg', models.TextField()),
                ('letrehozva', models.DateTimeField(auto_now_add=True)),
                ('felhasznalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['letrehozva'],
            },
        ),
    ]
