# Generated by Django 5.2.7 on 2026-05-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatuzenet'),
    ]

    operations = [
        migrations.AddField(
            model_name='feladat',
            name='kviz_kerdesek',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feladat',
            name='tipus',
            field=models.CharField(choices=[('szoveges', 'Szöveges'), ('kviz', 'Kvíz')], default='szoveges', max_length=10),
        ),
    ]
