# Generated by Django 5.2.7 on 2026-05-09 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_feladat_kviz_kerdesek_feladat_tipus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hianyzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Dátum')),
                ('igazolt', models.BooleanField(default=False, verbose_name='Igazolt')),
                ('megjegyzes', models.TextField(blank=True, null=True, verbose_name='Megjegyzés')),
                ('letrehozva', models.DateTimeField(auto_now_add=True)),
                ('diak', models.ForeignKey(limit_choices_to={'role': 'diak'}, on_delete=django.db.models.deletion.CASCADE, related_name='hianyzasok', to=settings.AUTH_USER_MODEL)),
                ('kurzus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hianyzasok', to='api.kurzus')),
                ('rogzito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rogzitett_hianyzasok', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hiányzások',
                'ordering': ['-datum'],
                'unique_together': {('diak', 'kurzus', 'datum')},
            },
        ),
    ]
